### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by CrazyCoderShi** [alibaba/flutter-common-widgets-app#20]
### 代码规范
>这个Repo真的非常棒，但是代码规范上使得该项目略显瑕疵.
> 我个人认为，作为一个实例Demo，至少在代码规范上至少能符合官方规范,该项目单单编译器提示出来的各种问题多达280+...
> [官方规范](https://www.dartlang.org/guides/language/effective-dart)

**Comment by Nealyang** [comment]
这个问题我们已经提上日程了，近期就会做一个规范化调整

**Comment by CrazyCoderShi** [comment]
@Nealyang 考虑到'国情'，很多同学可能会直接复制你们的代码的:joy:...
