### ISSUE TITLE
请求关于Dart的手册

### ISSUE THREAD

**Issue by maicss** [alibaba/flutter-common-widgets-app#7]
Dart中文资源的那个网站好像弃坑了，现在好像没有实时的中文资源。能不能也弄一个手册什么的呢，小白表示先谢谢了

**Comment by Nealyang** [comment]
好想法呀！老板说坑位已经给你预备了，就等你的pr了

**Comment by maicss** [comment]
说的就是小白手册，我要是能提pr还要求你们做么……，sigh，只怪自己笨咯

**Comment by Nealyang** [comment]
哈哈，别误会啊，后面我们菜鸟手册希望能大家一起共建，也非常欢迎大家可以提出好的想法、甚至pr我们都会积极采纳的。
